apiVersion: v1
kind: Namespace
metadata:
  name: blue-green
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
  namespace: blue-green
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Blue-Green Deployment</title>
      <style>
        body {
          font-family: Arial, sans-serif;
          background-color: #0f172a;
          color: white;
          text-align: center;
          padding-top: 100px;
        }
        h1 { color: #38bdf8; }
      </style>
    </head>
    <body>
      <h1>🚀 Blue-Green Rollout Preview</h1>
      <p>Served by nginx via Argo Rollouts</p>
    </body>
    </html>
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: blue-green
  namespace: blue-green
spec:
  replicas: 2
  strategy:
    blueGreen:
      activeService: blue-green
      previewService: blue-green-preview
      autoPromotionEnabled: false
  selector:
    matchLabels:
      app: blue-green
  template:
    metadata:
      labels:
        app: blue-green
    spec:
      containers:
      - name: nginx
        image: nginx:1.28.1-alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html
        configMap:
          name: nginx-html
---
apiVersion: v1
kind: Service
metadata:
  name: blue-green
  namespace: blue-green
spec:
  selector:
    app: blue-green
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: blue-green-preview
  namespace: blue-green
spec:
  selector:
    app: blue-green
  ports:
    - port: 80
      targetPort: 80
